# Generated by Django 2.1.5 on 2019-02-03 17:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("file_name", models.CharField(max_length=100)),
                ("file_size", models.IntegerField(null=True)),
                ("file_hash", models.CharField(max_length=64)),
                ("downloaded", models.BooleanField()),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("serial_number", models.CharField(db_index=True, max_length=20)),
                ("title", models.CharField(max_length=100)),
                ("writer", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("view", models.IntegerField()),
                ("content", models.TextField()),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="attachment",
            name="notice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="notice.Notice"
            ),
        ),
    ]
