# Generated by Django 2.1.5 on 2019-02-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("notice", "0001_initial")]

    operations = [migrations.RemoveField(model_name="attachment", name="file_hash")]
