# Generated by Django 2.1.5 on 2019-02-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("notice", "0002_remove_attachment_file_hash")]

    operations = [migrations.RemoveField(model_name="attachment", name="file_size")]
